server:
  port: 8001

spring:
  application:
    name: forex-rates-service

  jpa:
    show-sql: true
    h2:
      console:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
          defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

