server:
  port: 9001

spring:
  application:
    name: forex-converter-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
          defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 1
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
  ServerListRefreshInterval: 3000
